version: "3"

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/pg-Dockerfile
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: >
        postgres
        -c shared_buffers=1GB
        -c effective_cache_size=2GB
        -c maintenance_work_mem=512MB
        -c checkpoint_completion_target=0.9
        -c wal_buffers=64MB
        -c synchronous_commit=off
        -c fsync=off
        -c full_page_writes=off
        
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 5s
      retries: 5

  subquery-node:
    image: saurabhburade/subql-cosmos-node-test:v1.0.2

    restart: unless-stopped
    environment:
      DB_USER: postgres
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - ${SUB_COMMAND:-} # set SUB_COMMAND env variable to "test" to run tests
      - -f=/app
      - --db-schema=app
      - --workers=5
      - --batch-size=20
      - --unsafe=true
      - --allow-schema-migration
      - --scale-batch-size
      - --unfinalized-blocks=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://subquery-node:3000/ready"]
      interval: 13s
      timeout: 60s
      retries: 10

  graphql-engine:
    image: subquerynetwork/subql-query:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      DB_USER: postgres
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=app
      - --playground
